---
dc_name: dc1
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$FcnWHLB2gNYfpAfL$iXc84kPRere8LRZiqQNiUJqZC/eKBED/h1zkswu7GgHerBcK4O1PwLn7RSVPUDWNsBiNpN/DpMN4WFpsKsmYO."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."

#CVP terminattr config
# cvp_instance_ip: 192.168.1.209
# cvp_ingestauth_key: ''
# cvp_token_file: '/tmp/cv-onboarding-token'
daemon_terminattr:
  clusters: # For multiple cluster support
    cvaas:
      cvaddrs:
        - apiserver.cv-staging.corp.arista.io:443
      cvauth:
        method: "token-secure"
        token_file: "/tmp/cv-onboarding-token"
      cvvrf: default
    # cvp:
    #   cvaddrs:
    #     - 192.168.1.209:9910
    #   cvauth:
    #     method: "key"
    #     key: ""
    #   cvvrf: default
  disable_aaa: true
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"

# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_interface_vrf: default
mgmt_gateway: 10.255.0.1

# dns servers
name_servers:
  - 10.255.0.2

# logging
logging:
  console: "critical"
  monitor: "informational" 

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
custom_structured_configuration_ntp:
  servers:
    - name: time.google.com
      preferred: true
