---

- name: Build Switch configuration
  hosts: dc1_fabric
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intended variables
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      ansible.builtin.import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cvaas
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'dc1_fabric'
        configlets_prefix: 'avd'
        device_filter: 'dc1'
        state: present
