---
- name: "Collect EOS commands from devices"
  hosts: dc1_fabric
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: Collect show commands and generate reports
      ansible.builtin.import_role:
        name: arista.avd.eos_snapshot
