---
- name: Configuration deployment with CVP
  hosts: cvaas
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:
    - name: run CVP provisioning
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'dc1_fabric'
        configlets_prefix: 'avd'
        device_filter: 'dc1'
        cv_collection: v3
        state: present
