# This is a basic workflow to help you get started with Actions

name: Build action CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container: 
      image: avdteam/avd-all-in-one
      volumes:
        - /home/doot/actions-runner/_work/arista-ci:/home/avd/projects/
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      # Building the new configuration in the output directory
      - name: run playbook
        shell: bash
        run: echo "ansible-playbook -i arista-ci/inventory/inventory.yml arista-ci/playbooks/pb_build_config.yml --tags build"
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: build-intended
          path: ~/arista-ci/inventory/intended/
          
